---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: sbeliakou/centos-6.7-x86_64
   

suites:
  - name: default
    run_list: [
      'recipe[java17]',
      'recipe[nginx]',
      'recipe[tomcat]',
      'recipe[jenkins]'
      ]
    attributes:
